### PR TITLE
Alt language selector

### PR DESCRIPTION
**Pull request by SteveBarnett**
I'm not entirely happy using "&rarr;" for "more languages." For one thing, we need to flip it for RTL languages. For another, arrows are already used in interfaces for directional movement, which this is not.

How about "&hellip;" ?

### CODE REVIEW

**Comment by SteveBarnett** [comment]
This will apply to all UC sites, btw.

**Comment by jonthemac** [comment]
Yo Steve. Is there a reason we aren't happy to use the word 'more'? Or even 'More...'. Is it because it needs to be translated? (the names of the actual languages need to be translated too sometimes, as is the case with the Indian languages, so I don't know if this is an actual barrier. The only reason I'm asking is because I'm not sure if the '...' convention will be well known to these users. I definitely prefer the '...' to the arrow though. = my two cents

**Comment by SteveBarnett** [comment]
@jonthemac: yeah, "more" doesn't feel right. Nor "Change". An icon feels better. Ideally, I would want to test this, of course. Get it in front of some users with a couple of variations, see what happens.

Let's push "..." out, then, and monitor what happens in the analytics.

**Comment by SteveBarnett** [comment]
@miltontony Are you happy with that?

**Comment by miltontony** [comment]
:+1:

**Pull request merged**
