### PR TITLE
Need to update css for RTL

### PR DESCRIPTION
**Pull request by nathanbegbie**

### CODE REVIEW

**Comment by nathanbegbie** [comment]
@SteveBarnett: oversight please

**Comment by SteveBarnett** [comment]
:+1:, Mr B.

**Comment by nathanbegbie** [comment]
@miltontony: OK, so should I go ahead and merge and then we wait for response from testers to see if we should change the alignment? I think we may have a similar issue with font size in terms of legibility.

**Comment by miltontony** [comment]
:+1:

**Comment by nathanbegbie** [comment]
@SteveBarnett do I need to change the CSS reference from `?v=20150128` to `?v=20150129` before I merge? Not sure if I understood what that was all about.

**Comment by SteveBarnett** [comment]
@nathanbegbie If the 20150128 one has been pushed to a server somewhere: _yes_. If it's only been sitting on GitHub: _no_.

**Pull request merged**
